---

name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Continuous integration
    timeout-minutes: 10

    env:
      MAIN_BRANCH: master
      MAJOR_VERSION: 2.5
      CI: true
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin

    steps:
      # Versions
      - run: docker --version
      - uses: actions/checkout@v2

      - run: make pull
      - run: make build
      - run: make acceptance
      - run: (cd acceptance_tests/ && docker-compose logs)
        if: failure()

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-mapserver'
      - name: Publish to Docker hub
        run: ci/publish
        if: github.repository == 'camptocamp/docker-mapserver'
