---

name: Rebuild

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - '7.0'
          - '7.2'
          - '7.4'
          - '7.6'

    env:
      MAIN_BRANCH: master
      MAJOR_VERSION: 2.5
      CI: true
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin

    steps:
      # Versions
      - run: docker --version
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}

      - run: make pull
      - run: make build
      - run: make acceptance

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-mapserver'
      - name: Publish to Docker hub
        run: ci/publish ${{ matrix.branch }}
        if: github.repository == 'camptocamp/docker-mapserver'
